import { DataTypes, QueryInterface } from 'sequelize';

/** @type {import("sequelize-cli").Migration} */
export default {
  async up(queryInterface: QueryInterface): Promise<void> {
    await queryInterface.sequelize.transaction(async (transaction) => {
      await queryInterface.createTable('Guidelines', {
        id: {
          type: DataTypes.INTEGER,
          primaryKey: true,
          allowNull: false,
          autoIncrement: true,
        },
        content: {
          type: DataTypes.TEXT,
          allowNull: false,
        },
        embeddings: {
          type: 'vector(1536)', //1536 are the dimensions of the embeddings generated by openai text-embedding-3-small model
          allowNull: false,
        },
        createdAt: {
          type: DataTypes.DATE,
        },
        updatedAt: {
          type: DataTypes.DATE,
        },
      });
    });
  },

  async down(queryInterface: QueryInterface): Promise<void> {
    await queryInterface.sequelize.transaction(async (transaction) => {
      //your code here
      await queryInterface.dropTable('Guidelines');
    });
  },
};
